from glob import glob
import pandas as pd
import json
import sys

from scripts.common.helpers import get_spades_mode, get_assembly_path, \
    get_assembly_type, get_quast_stats, get_fastp_stats, get_nanostat_stats

configfile: "workflow/config/config.yaml"

containers = config['containers']

include: "rules/samples_variables.smk"
include: "rules/database_variables.smk"
include: "rules/output_variables.smk"
include: "rules/download_rules.smk"
include: "rules/qc_rules.smk"
include: "rules/assembly_rules.smk"
include: "rules/post_assembly_rules.smk"
include: "rules/summary_rules.smk"

rule all:
    input: OUTPUTS
