from glob import glob
import pandas as pd
import json

configfile: "workflow/config/config.yaml"

################################################################################
#
# Containers...
#
################################################################################

containers = {
    "fastp": "docker://quay.io/biocontainers/fastp:1.1.0--heae3180_0",
    "fastqc": "docker://quay.io/biocontainers/fastqc:0.12.1--hdfd78af_0",
    "chopper": "docker://quay.io/biocontainers/chopper:0.12.0--hcdda2d0_0",
    "nanostat": "docker://quay.io/biocontainers/nanostat:1.6.0--pyhdfd78af_0",
    "kraken2": "docker://quay.io/biocontainers/kraken2:2.17.1--pl5321h077b44d_0",
    "spades": "docker://simonbrandt/spades:v4.2.0",
    "flye": "docker://quay.io/biocontainers/flye:2.9.6--py311h2de2dd3_0",
    "unicycler": "docker://quay.io/biocontainers/unicycler:0.5.1--py39h746d604_5",
    "bakta": "docker://quay.io/biocontainers/bakta:1.12.0--pyhdfd78af_0",
    "blast": "docker://quay.io/biocontainers/blast:2.17.0--h66d330f_0",
    "gtdbtk": "docker://quay.io/biocontainers/gtdbtk:2.6.1--pyh1f0d9b5_2",
    "checkm2": "docker://quay.io/biocontainers/checkm2:1.1.0--pyh7e72e81_1",
    "busco": "docker://ezlabgva/busco:v6.0.0_cv1",
    "quast": "docker://quay.io/biocontainers/quast:5.3.0--py313pl5321h5ca1c30_2",
    "multiqc": "docker://quay.io/biocontainers/multiqc:1.33--pyhdfd78af_0"
}

################################################################################
#
# Helper functions for dynamic parameters and outputs
#
################################################################################

def get_spades_mode(wildcards, input):
    """
    Determine SPAdes mode based on estimated coverage from input FASTQ files.
    """
    # Estimate total bases: Gzipped FASTQ is roughly 1 byte per base 
    # (conservative estimate including quality scores and headers)
    file_size_bytes = os.path.getsize(input.fq1) + os.path.getsize(input.fq2)
    estimated_coverage = file_size_bytes / config['genome_size']
    
    if estimated_coverage > 100:
        return "--isolate"
    else:
        return "--careful"

def get_assembly_path(wildcards):
    """
    Resolve the assembly path based on the sample type (long or short).
    """
    if wildcards.sample in SHORT_SAMPLES:
        return f"results/assembly/short_assembly/{wildcards.sample}.fasta"
    else:
        return f"results/assembly/long_assembly/{wildcards.sample}.fasta"

def get_assembly_type(wildcards):
    """
    Return the assembly type (short or long) based on the sample.
    """
    if wildcards.sample in LONG_SAMPLES:
        return "long"
    else:
        return "short"

def get_quast_stats(quast_report,log):
    """
    Extracts key statistics from QUAST report. 

    Required parameters:
        quast_report: Path to the QUAST report.tsv file
        log: Path to log file

    Returns:
        A dictionary with keys: 'assembly_size', 'num_contigs', 'gc_content', 'n50'
    """
    with open(log[0], 'a') as log_file:
        log_file.write(f"Extracting QUAST stats from {quast_report}\n")

        quast_df = pd.read_csv(quast_report, sep='\t', header=None)
        log_file.write("QUAST report loaded successfully.\n")

        quast_df.set_index(0,inplace=True)
        quast_df = quast_df.transpose()

        stats = {
            "assembly_size": int(quast_df['Total length'].values[0]),
            "num_contigs": int(quast_df['# contigs'].values[0]),
            "gc_content": float(quast_df['GC (%)'].values[0]),
            "n50": int(quast_df['N50'].values[0])
        }

        log_file.write("QUAST stats extracted:\n")
        for key, value in stats.items():
            log_file.write(f"{key}: {value}\n")

    return stats

def get_fastp_stats(fastp_json, log):
    """
    Extracts key statistics from fastp JSON report.

    Required parameters:
        fastp_json: Path to the fastp JSON report file
        log: Path to log file

    Returns:
        A dictionary with keys: 'total_bases', 'total_reads', 'q20_bases', 'q30_bases'
    """
    with open(log[0], 'a') as log_file:
        log_file.write(f"Extracting fastp stats from {fastp_json}\n")

        with open(fastp_json) as f:
            data = json.load(f)

        stats = {
            "total_bases": int(data['summary']['after_filtering']['total_bases']),
            "total_reads": int(data['summary']['after_filtering']['total_reads']),
        }

        log_file.write("fastp stats extracted:\n")
        for key, value in stats.items():
            log_file.write(f"{key}: {value}\n")

    return stats

def get_nanostat_stats(nanostat_report, log):
    """
    Extracts key statistics from NanoStat report.

    Required parameters:
        nanostat_report: Path to the NanoStat report file
        log: Path to log file

    Returns:
        A dictionary with keys: 'total_bases', 'total_reads', 'mean_length', 'n50'
    """
    with open(log[0], 'a') as log_file:
        log_file.write(f"Extracting NanoStat stats from {nanostat_report}\n")


        nanostat_df = pd.read_csv(nanostat_report, sep='\t')
        log_file.write("NanoStat report loaded successfully.\n")

        nanostat_df.set_index('Metrics',inplace=True)
        nanostat_df = nanostat_df.transpose()
        int(float(nanostat_df['number_of_bases'].values[0]))

        stats = {
            "total_bases": int(float(nanostat_df['number_of_bases'].values[0])),
            "total_reads": int(float(nanostat_df['number_of_bases'].values[0])),
            "mean_length": int(float(nanostat_df['mean_read_length'].values[0])),
            "n50": int(float(nanostat_df['n50'].values[0])),
        }

        log_file.write("NanoStat stats extracted:\n")
        for key, value in stats.items():
            log_file.write(f"{key}: {value}\n")

    return stats

################################################################################
#
# Sample and database configuration
#
################################################################################

# Each sample should be in a subdirectory of 'data/' named with the sample id,
# and containing 'short_reads/' and/or 'long_reads/' subdirectories with the
# appropriate FASTQ files.

# Filenaming should start with the sample id, and end with '_1.fastq.gz' and
# '_2.fastq.gz' for short reads, and '{sample}.fastq.gz' for long reads.

SAMPLES = glob('data/*')
SAMPLES = [os.path.basename(x) for x in SAMPLES]
LONG_SAMPLES = []
SHORT_SAMPLES = []

for sample in SAMPLES:
    if os.path.exists(f"data/{sample}/long_reads"):
        LONG_SAMPLES.append(sample)
    else:
        SHORT_SAMPLES.append(sample)

BAKTA_DB_PATH = "databases/bakta_db/db"

# Bakta database consists of multiple files with different extensions depending on the type of data
BAKTA_DB_MAP = {
    "hmmer": (["antifam", "pfam"], [".h3f", ".h3i", ".h3m", ".h3p"]),
    "infernal": (["ncRNA-genes", "ncRNA-regions", "rRNA"], [".i1i", ".i1f", ".i1m", ".i1p"]),
    "singletons": [
        "bakta.db", "expert-protein-sequences.dmnd", "sorf.dmnd", 
        "oric.fna", "orit.fna", "rfam-go.tsv", "version.json"
    ]
}

BAKTA_DB = (
    [f"{BAKTA_DB_PATH}/{p}{ext}" for p, exts in [BAKTA_DB_MAP["hmmer"], BAKTA_DB_MAP["infernal"]] for p in p for ext in exts] +
    [f"{BAKTA_DB_PATH}/{f}" for f in BAKTA_DB_MAP["singletons"]]
)

# Kraken2 database files...
KRAKEN_DB_MAP=  { "kmers": [50,75,100,150,200,250,300],
                  "k2d": ["hash", "opts", "taxo" ],
                  "dmp": ["names", "nodes"],
                  "txt": ["inspect", "unmapped_accessions"],
                  "tsv": ["ktaxonomy", "library_report"] } 

KRAKEN_DB_PATH = "databases/kraken2"
KRAKEN_DB = ( [f"{KRAKEN_DB_PATH}/database{kmers}mers.kmer_distrib" for kmers in KRAKEN_DB_MAP["kmers"]] +
              [f"{KRAKEN_DB_PATH}/{k2d}.k2d" for k2d in ["hash", "opts", "taxo"]] +
              [f"{KRAKEN_DB_PATH}/{dmp}.dmp" for dmp in KRAKEN_DB_MAP["dmp"]] +
              [f"{KRAKEN_DB_PATH}/{txt}.txt" for txt in KRAKEN_DB_MAP["txt"]] +
              [f"{KRAKEN_DB_PATH}/{tsv}.tsv" for tsv in KRAKEN_DB_MAP["tsv"]] +
              [f"{KRAKEN_DB_PATH}/seqid2taxid.map"] )

AMRFINDER_DB=f'{BAKTA_DB_PATH}/amrfinderplus-db/latest/version.txt'

BUSCO_DB = "databases/busco_lineages/download.complete"
CHECKM2_DB = "databases/checkm2_db/uniref100.KO.1.dmnd"

# Way too many files in GTDB to list them all, so just one as a target
GTDB = ['databases/gtdbtk/taxonomy/gtdb_taxonomy.tsv']

################################################################################
# 
# Define outputs...
#
################################################################################
NANO_TRIMMED = expand("results/long_read_stats/{sample}_trimmed_nanostat.txt", sample=LONG_SAMPLES)

SHORT_ASSEMBLIES = expand("results/assembly/short_assembly/{sample}.fasta",sample=SHORT_SAMPLES)
LONG_ASSEMBLIES = expand("results/assembly/long_assembly/{sample}.fasta",sample=LONG_SAMPLES)

KRAKEN_REPORTS = expand("results/kraken2/{sample}_kraken_report.txt", sample=SAMPLES)

ANNOT_EXTS = ['.tsv', '.gff3', '.gbff', '.embl', '.fna', 
              '.ffn', '.faa', '.hypotheticals.tsv', '.txt', '.json']
ANNOTS = expand(
    "results/annotated/{sample}/{sample}{ext}", 
    sample=SAMPLES, 
    ext=ANNOT_EXTS
)

BLAST_GENOMIC_SUFFIXES = ['','.ndb', '.nhr', '.nin', '.njs', '.not', '.nsq', '.ntf', '.nto']
BLAST_PROTEIN_SUFFIXES = ['','.pdb', '.phr', '.pin', '.pjs', '.pot', '.psq', '.ptf', '.pto']

BLAST_GENOMIC = expand("results/blast_db/genome/{sample}{suffix}", 
    sample=SAMPLES, suffix=BLAST_GENOMIC_SUFFIXES)
BLAST_PROTEIN = expand("results/blast_db/protein/{sample}{suffix}", 
    sample=SAMPLES, suffix=BLAST_PROTEIN_SUFFIXES)

BLAST_ALIAS_DBS = [
    "results/blast_db/assemblies.nal",
    "results/blast_db/assemblies.pal"
]

FASTQC_OUTPUTS = expand("results/fastqc/{sample}_{read}_fastqc.zip",
    sample=SAMPLES,
    read=[1,2]
)
BUSCOS=expand("results/busco/short_summary_{sample}.txt",
    sample=SAMPLES)
CHECKMS = expand("results/checkm2/{sample}/quality_report.tsv", 
    sample=SAMPLES)
GTDBTK = ['results/gtdbtk/gtdbtk.bac120.summary.tsv']
QUASTS=expand("results/quast/{sample}/report.tsv",sample=SAMPLES)
MULTIQC_REPORT = ['workflow/reports/multiqc_report.html']

MANIFESTS = expand("results/manifests/{sample}_manifest.tsv", sample=SAMPLES)

OUTPUTS = ANNOTS + BLAST_ALIAS_DBS + BUSCOS + GTDBTK + QUASTS + \
    CHECKMS + FASTQC_OUTPUTS + MULTIQC_REPORT + MANIFESTS

################################################################################
#
# Define rules
#
################################################################################

rule all:
    input: OUTPUTS

rule kraken_db_download:
    output: KRAKEN_DB
    log: 'workflow/logs/kraken_db_download.log'
    params:
        kraken_db_version = config['kraken_db_version']
    shell:"""
mkdir -p databases/kraken2
bin/download_krakendb.py --version {params.kraken_db_version} > {log} 2>&1
ls -l databases/kraken2/ >> {log} 2>&1
"""

rule bakta_download:
    output: BAKTA_DB
    container: containers["bakta"]
    shell:"""
mkdir -p databases/bakta_db
bakta_db download --output databases/bakta_db
"""

rule amrfinder_download:
    input: BAKTA_DB
    output: AMRFINDER_DB	
    container: containers["bakta"]
    shell:"""
    amrfinder_update --database databases/bakta_db/db/amrfinderplus-db/
"""

rule gtdb_download:
    output: GTDB
    params:
        gtdb_version = config['gtdb_version']
    log: 'workflow/logs/gtdb_download.log'
    shell: """
bin/download_gtdbtk_db.py \
  --release {params.gtdb_version} \
  > {log} 2>&1
"""

rule busco_download:
    output: BUSCO_DB
    log: 'workflow/logs/busco_download.log'
    shell: """
    bin/download_busco_lineages.py > {log} 2>&1
    touch {output}
"""

rule checkm2_download:
    output: CHECKM2_DB
    log: 'workflow/logs/checkm2_download.log'
    shell: """
    mkdir -p databases/checkm2_db
    wget https://zenodo.org/records/14897628/files/checkm2_database.tar.gz?download=1 \
        -O databases/checkm2_db/checkm2_database.tar.gz
    tar -xzf databases/checkm2_db/checkm2_database.tar.gz -C databases/checkm2_db/ --strip-components=1
    rm databases/checkm2_db/checkm2_database.tar.gz
"""

rule fastqc:
    input:
        fq1 = 'data/{sample}/short_reads/{sample}_1.fastq.gz',
        fq2 = 'data/{sample}/short_reads/{sample}_2.fastq.gz'
    output:
        fq1 = 'results/fastqc/{sample}_1_fastqc.zip',
        fq2 = 'results/fastqc/{sample}_2_fastqc.zip'
    container: containers["fastqc"]
    log: 'workflow/logs/fastqc_{sample}.log'
    shell: """
        fastqc \
            -o results/fastqc/ \
            {input.fq1} \
            {input.fq2} \
        > {log} 2>&1
    """

rule fastp:
    input:
        fq1 = 'data/{sample}/short_reads/{sample}_1.fastq.gz',
        fq2 = 'data/{sample}/short_reads/{sample}_2.fastq.gz'
    output:
        fq1 = 'results/trimmed_short_reads/{sample}_1.fastq.gz',
        fq2 = 'results/trimmed_short_reads/{sample}_2.fastq.gz',
        json = 'results/trimmed_short_reads/{sample}_fastp.json'
    container: containers["fastp"]
    threads: 1 # overidden by profile config, but required...
    log: 'workflow/logs/fastp_{sample}.log'
    shell: """
        fastp \
            -i {input.fq1} \
            -I {input.fq2} \
            -o {output.fq1} \
            -O {output.fq2} \
            --json {output.json} \
            --html /dev/null \
            --thread {threads} \
            --disable_quality_filtering \
            --disable_length_filtering \
        > {log} 2>&1
    """

rule chopper:
    input:
        long_reads = 'data/{sample}/long_reads/{sample}.fastq.gz'
    output:
        filtered_reads = 'results/trimmed_long_reads/{sample}.fastq.gz'
    container: containers["chopper"]
    threads: 1 # overidden by profile config, but required...
    params:
        min_qual = 10,   # Minimum average Phred score
        min_len = 1000   # Minimum read length (bp)
    log: 'workflow/logs/chopper_{sample}.log'
    shell:
        """
        gunzip -c {input.long_reads} | \
        chopper -t {threads} -q {params.min_qual} -l {params.min_len} | \
        gzip > {output.filtered_reads} 2> {log}
        """

rule nanostat:
    input: 'data/{sample}/long_reads/{sample}.fastq.gz'
    output: 'results/long_read_stats/{sample}_nanostat.txt'
    container: containers["nanostat"]
    log: 'workflow/logs/nanostat_{sample}.log'
    threads: 1 # overidden by profile config, but required...
    shell: """
        NanoStat \
            --fastq {input} \
            --name {output} \
            --threads {threads} \
            --tsv \
        > {log} 2>&1
    """

rule nanostat_trimmed:
    input: 'results/trimmed_long_reads/{sample}.fastq.gz'
    output: 'results/long_read_stats/{sample}_trimmed_nanostat.txt'
    container: containers["nanostat"]
    log: 'workflow/logs/nanostat_{sample}.log'
    threads: 1 # overidden by profile config, but required...
    shell: """
        NanoStat \
            --fastq {input} \
            --name {output} \
            --threads {threads} \
            --tsv \
        > {log} 2>&1
    """

rule kraken:
    input: 
        r1 = 'results/trimmed_short_reads/{sample}_1.fastq.gz', 
        r2 = 'results/trimmed_short_reads/{sample}_2.fastq.gz',
        db = KRAKEN_DB
    output: 
        output = 'results/kraken2/{sample}_kraken_output.txt',
        report = 'results/kraken2/{sample}_kraken_report.txt'
    container: containers["kraken2"]
    log: 'workflow/logs/kraken2_{sample}.log'
    threads: 1 # overidden by profile config, but required...
    shell: """
    k2 classify \
        --db databases/kraken2/ \
        --threads {threads} \
        --memory-mapping \
        --use-names \
        --output {output.output} \
        --report {output.report} \
        --paired \
        {input.r1} {input.r2} > {log} 2>&1
    """

rule spades:
    input:
        fq1 = 'results/trimmed_short_reads/{sample}_1.fastq.gz',
        fq2 = 'results/trimmed_short_reads/{sample}_2.fastq.gz'
    output: 
        contigs = "results/assembly/short_assembly/{sample}.fasta",
        gfa = "results/assembly/short_assembly/{sample}.gfa"
    container: containers["spades"]
    log: 'workflow/logs/spades_{sample}.log'
    threads: 1 # overidden by profile config, but required...
    resources:
        mem_mb = 1 # overidden by profile config, but required...
    params:
        mode = get_spades_mode
    shell: """
        (cp -v {input.fq1} $TMPDIR/{wildcards.sample}_1.fastq.gz &&
        cp -v {input.fq2} $TMPDIR/{wildcards.sample}_2.fastq.gz &&
        spades.py \
            -1 $TMPDIR/{wildcards.sample}_1.fastq.gz \
            -2 $TMPDIR/{wildcards.sample}_2.fastq.gz \
            {params.mode} \
            -t {threads} \
            -m {resources.mem_mb} \
            -o $TMPDIR/spades_output &&
        cp -v $TMPDIR/spades_output/contigs.fasta {output.contigs} &&
        cp -v $TMPDIR/spades_output/assembly_graph_with_scaffolds.gfa {output.gfa} ) \
        > {log} 2>&1 
    """

rule flye:
    input: 
        fastq="results/trimmed_long_reads/{sample}.fastq.gz",
        stats="results/long_read_stats/{sample}_trimmed_nanostat.txt" 
    output: 
        assembly = "results/flye/{sample}.fasta",
        gfa = "results/flye/{sample}.gfa",
        info = "results/flye/{sample}_assembly_info.txt"
    container: containers["flye"]
    log: 'workflow/logs/flye_{sample}.log'
    threads: 1 # overidden by profile config, but required...
    resources:
        mem_mb = 1 # overidden by profile config, but required...
    params:
        genome_size = config['genome_size']
    shell: """
        (cp -v {input.fastq} $TMPDIR &&
        flye \
            --nano-hq $TMPDIR/{wildcards.sample}.fastq.gz \
            --out-dir $TMPDIR/flye \
            --genome-size {params.genome_size} \
            --asm-coverage 50 \
            --threads {threads} &&
        cp -v $TMPDIR/flye/assembly.fasta {output.assembly} &&
        cp -v $TMPDIR/flye/assembly_graph.gfa {output.gfa} &&
        cp -v $TMPDIR/flye/assembly_info.txt {output.info} ) \
        > {log} 2>&1
    """

rule unicycler:
    input: 
        short_fq1 = 'results/trimmed_short_reads/{sample}_1.fastq.gz',
        short_fq2 = 'results/trimmed_short_reads/{sample}_2.fastq.gz',
        long_fq = 'results/trimmed_long_reads/{sample}.fastq.gz',
        flye_contigs = 'results/flye/{sample}.fasta'
    output: 
        contigs = "results/assembly/long_assembly/{sample}.fasta",
            gfa = "results/assembly/long_assembly/{sample}.gfa" 
    container: containers["unicycler"]
    log: 'workflow/logs/unicycler_{sample}.log'
    threads: 1 # overidden by profile config, but required...
    resources:
        mem_mb = 1 # overidden by profile config, but required... 
    shell:"""
        ( mkdir $TMPDIR/reads &&
        cp -v {input.short_fq1} $TMPDIR/reads/{wildcards.sample}_1.fastq.gz &&
        cp -v {input.short_fq2} $TMPDIR/reads/{wildcards.sample}_2.fastq.gz &&
        cp -v {input.long_fq} $TMPDIR/reads/{wildcards.sample}.fastq.gz &&
        cp -v {input.flye_contigs} $TMPDIR/reads/flye.fasta &&
        unicycler \
            -1 $TMPDIR/reads/{wildcards.sample}_1.fastq.gz \
            -2 $TMPDIR/reads/{wildcards.sample}_2.fastq.gz \
            -l $TMPDIR/reads/{wildcards.sample}.fastq.gz \
            --existing_long_read_assembly $TMPDIR/reads/flye.fasta \
            -t {threads} \
            --mode bold \
            -o $TMPDIR/output &&
        cp -v $TMPDIR/output/assembly.fasta {output.contigs} &&
        cp -v $TMPDIR/output/assembly.gfa {output.gfa} ) \
        > {log} 2>&1
    """

rule bakta:
    input: 
        contigs=get_assembly_path,
        db=AMRFINDER_DB # Ensure AMRFinder (and therefore bakta) database is available before running annotation...
    output:
        multiext("results/annotated/{sample}/{sample}",'.tsv','.gff3',
            '.gbff','.embl','.fna','.ffn','.faa','.hypotheticals.tsv','.txt','.json')
    container: containers["bakta"]
    log: 'workflow/logs/bakta_{sample}.log'
    params:
        gram=config['gram']
    threads: 1 # overidden by profile config, but required...
    shell:"""
        bakta \
        --db databases/bakta_db/db \
        --prefix {wildcards.sample} \
        --output results/annotated/{wildcards.sample} \
        --threads {threads} \
        --complete \
        --compliant \
        --locus-tag {wildcards.sample} \
        --gram {params.gram} \
        --force \
        {input.contigs} > {log} 2>&1
"""

rule blast_format:
    input: 
        genome="results/annotated/{sample}/{sample}.fna",
        protein="results/annotated/{sample}/{sample}.faa"
    output: 
        genome=multiext("results/blast_db/genome/{sample}",'','.ndb', '.nhr', '.nin', '.njs', '.not', '.nsq', '.ntf', '.nto'),
        protein=multiext("results/blast_db/protein/{sample}",'','.pdb', '.phr', '.pin', '.pjs', '.pot', '.psq', '.ptf', '.pto')
    container: containers["blast"]
    log: 'workflow/logs/blast_format_{sample}.log'
    shell: """
        cat {input.genome} |  sed -E 's/(contig_[0-9]*).*/{wildcards.sample}|\\1/' > \
            results/blast_db/genome/{wildcards.sample}
        cp {input.protein} results/blast_db/protein/{wildcards.sample}

        makeblastdb \
            -in results/blast_db/genome/{wildcards.sample} \
            -dbtype nucl \
            -out results/blast_db/genome/{wildcards.sample} \
            > {log} 2>&1

        makeblastdb \
            -in results/blast_db/protein/{wildcards.sample} \
            -dbtype prot \
            -out results/blast_db/protein/{wildcards.sample} \
            > {log} 2>&1
    """

rule combined_blast_db:
    input: BLAST_GENOMIC + BLAST_PROTEIN
    output:
        genome = "results/blast_db/assemblies.nal",
        protein = "results/blast_db/assemblies.pal"
    container: containers["blast"]
    log: 'workflow/logs/combined_blast_db.log'
    shell: """
    ls results/blast_db/genome|grep -v \\\\. | \
        sed 's|^|results/blast_db/genome/|' > $TMPDIR/genome_samples.txt

    ls  results/blast_db/protein|grep -v \\\\. | \
        sed 's|^|results/blast_db/protein/|' > $TMPDIR/protein_samples.txt

    blastdb_aliastool -dblist_file $TMPDIR/genome_samples.txt \
        -dbtype nucl \
        -title "Combined Genomic Assemblies" \
        -out results/blast_db/assemblies
        >> {log} 2>&1

    blastdb_aliastool -dblist_file $TMPDIR/protein_samples.txt \
        -dbtype prot \
        -title "Combined Protein Predictions" \
        -out results/blast_db/assemblies
        >> {log} 2>&1
    """


rule gtdbtk:
    input:
        assemblies = LONG_ASSEMBLIES + SHORT_ASSEMBLIES,
        database = GTDB
    output:
        "results/gtdbtk/gtdbtk.bac120.summary.tsv"
    container: containers["gtdbtk"]
    threads: 1 # overidden by profile config, but required...
    log: 'workflow/logs/gtdbtk.log'
    shell: """
export GTDBTK_DATA_PATH="databases/gtdbtk"
gtdbtk classify_wf \
        --genome_dir results/assembly \
        --out_dir results/gtdbtk/ \
        -x fasta \
        --cpus {threads} \
        --pplacer_cpus {threads} \
        --tmpdir $TMPDIR \
        --force \
        > {log} 2>&1
"""

rule busco:
    input: 
        assembly = get_assembly_path,
        database = "databases/busco_lineages/download.complete"
    output: "results/busco/short_summary_{sample}.txt"
    container: containers["busco"]
    threads: 1 # overidden by profile config, but required...
    log: 'workflow/logs/busco_{sample}.log'
    shell: """
    cp -v {input.assembly} $TMPDIR/assembly.fasta 
    current_dir=$(pwd) 
    cd $TMPDIR
    busco -m genome \
        -c {threads} \
        --auto-lineage-prok \
        --download_path $current_dir/databases/busco_lineages \
        --out_path $TMPDIR \
        --offline \
        -o {wildcards.sample} \
        -i assembly.fasta \
        -f >> $current_dir/{log} 2>&1
        result=$(ls -rt $TMPDIR/{wildcards.sample}/*.txt|tail -1)
        cp -v $result $current_dir/{output} >> $current_dir/{log} 2>&1
"""

rule checkm2: 
    input: 
        assembly = get_assembly_path,
        database = CHECKM2_DB
    output: "results/checkm2/{sample}/quality_report.tsv"
    container: containers["checkm2"]
    threads: 1 # overidden by profile config, but required...
    log: 'workflow/logs/checkm2_{sample}.log'
    shell: """
    checkm2 predict \
        --input {input.assembly} \
        --output_dir results/checkm2/{wildcards.sample} \
        --database {input.database} \
        --threads {threads} \
        --force \
        --tmpdir $TMPDIR \
        > {log} 2>&1
"""

rule quast:
    input: 
        short_fq1 = 'results/trimmed_short_reads/{sample}_1.fastq.gz',
        short_fq2 = 'results/trimmed_short_reads/{sample}_2.fastq.gz',
        assembly=get_assembly_path
    output: "results/quast/{sample}/report.tsv"
    params:
        long_fq = 'results/trimmed_long_reads/{sample}.fastq.gz',
        genome_size = config['genome_size'] 
    container: containers["quast"]
    threads: 1 # overidden by profile config, but required...
    log: 'workflow/logs/quast_{sample}.log'
    shell: """
        mkdir $TMPDIR/reads
        cp {input.short_fq1} $TMPDIR/reads/{wildcards.sample}_1.fastq.gz
        cp {input.short_fq2} $TMPDIR/reads/{wildcards.sample}_2.fastq.gz

        job_args=""
        if [ -f {params.long_fq} ]; then
            cp -v {params.long_fq} $TMPDIR/reads/{wildcards.sample}.fastq.gz
            job_args="--nanopore $TMPDIR/reads/{wildcards.sample}.fastq.gz"
        fi

        quast \
        --pe1 $TMPDIR/reads/{wildcards.sample}_1.fastq.gz \
        --pe2 $TMPDIR/reads/{wildcards.sample}_2.fastq.gz \
        --features results/annotated/{wildcards.sample}/{wildcards.sample}.gff3 \
        $job_args \
        --est-ref-size {params.genome_size} \
        -l {wildcards.sample} \
        -o results/quast/{wildcards.sample} \
        --threads {threads} \
        --no-html \
        {input.assembly} > {log} 2>&1
"""
rule software_versions:
    output: 'results/software_mqc_versions.yaml'
    run:
        with open(output[0], 'w') as f:
            for name, container in containers.items():
                version = container.split(':')[-1].split('--')[0]
                f.write(f"{name}: {version}\n")

rule multiqc:
    input:
        files = expand('results/trimmed_short_reads/{sample}_fastp.json', sample=SAMPLES) +
                expand('results/long_read_stats/{sample}_nanostat.txt', sample=LONG_SAMPLES) +
                FASTQC_OUTPUTS + KRAKEN_REPORTS + ANNOTS + GTDBTK + CHECKMS + BUSCOS + QUASTS + 
                ['results/software_mqc_versions.yaml'],
        config = 'etc/multiqc.conf'
    output:
        'workflow/reports/multiqc_report.html'
    container: containers["multiqc"]
    log: 'workflow/logs/multiqc.log'
    shell:
        """
        multiqc results \
                --config etc/multiqc.conf \
                --outdir workflow/reports/ \
                --filename multiqc_report.html \
                --force > {log} 2>&1
        """

rule manifest:
    input: 
        fastp = 'results/trimmed_short_reads/{sample}_fastp.json',
        quast = "results/quast/{sample}/report.tsv"
    output: "results/manifests/{sample}_manifest.tsv"
    params: 
        nanostat = "results/long_read_stats/{sample}_trimmed_nanostat.txt",
    log: 'workflow/logs/manifest_{sample}.log'
    run:
        short_bases = 0
        long_bases = 0
        program = 'SPAdes' 

        # Load quast report
        assembly_stats = get_quast_stats(input.quast, log)
        assembly_size = assembly_stats['assembly_size']
        
        fastp_stats = get_fastp_stats(input.fastp, log)
        short_bases = fastp_stats['total_bases']

        if get_assembly_type(wildcards) == "long":
            nanostat_stats = get_nanostat_stats(params.nanostat, log)
            long_bases = nanostat_stats['total_bases']
            program = 'flye, unicycler'

        coverage = int((short_bases + long_bases) / assembly_size) if assembly_size > 0 else 0

        samples_file = Path('workflow/config/samples.csv')
        runs_file = Path('workflow/config/runs.csv')

        if samples_file.exists() and runs_file.exists():
            samples_df = pd.read_csv(samples_file)
            runs_df = pd.read_csv(runs_file)
            ena_df = samples_df.merge(runs_df, left_on='id', right_on='sampleId', how='outer', suffixes=('_samples', '_runs'))
            sample_info = ena_df[ena_df['alias_samples'] == wildcards.sample]

            sample_id = sample_info['id_samples'].values[0] if not sample_info.empty else None
            run_id = ','.join(sample_info['id_runs'].values) if not sample_info.empty else None

        # Combine into manifest
        manifest_df = pd.DataFrame({
            'STUDY': [config['project_id']],
            'SAMPLE': sample_id,
            'ASSEMBLY_NAME': [wildcards.sample],
            'ASSEMBLY_TYPE': 'isolate',
            'COVERAGE': coverage,
            'PROGRAM': program,
            'PLATFORM': config['short_read_instrument'] + (f", {config['long_read_instrument']}" \
                if long_bases > 0 else ""),
            'MOLECULE_TYPE': 'genomic DNA',
            'RUN_REF': run_id,
            'FLATFILE': f"{wildcards.sample}.embl"
        })

        manifest_df = manifest_df.transpose()
        manifest_df.to_csv(output[0], sep='\t', index=True, header=False)