from glob import glob
import os

genome_size = 5_000_000 # 5 Mbp, typical for Bacillus subtilis, and median-ish for Bacillus as a whole

def get_spades_mode(wildcards, input):
    """
    Determine SPAdes mode based on estimated coverage from input FASTQ files.
    """
    # Estimate total bases: Gzipped FASTQ is roughly 1 byte per base 
    # (conservative estimate including quality scores and headers)
    file_size_bytes = os.path.getsize(input.fq1) + os.path.getsize(input.fq2)
    estimated_coverage = file_size_bytes / genome_size
    
    if estimated_coverage > 100:
        return "--isolate"
    else:
        return "--careful"

CONDA_PREFIX=os.environ['CONDA_PREFIX']
BAKTA_DB_PATH="{}/bakta_db/db".format(CONDA_PREFIX)

SAMPLES=glob('data/*')
SAMPLES=[os.path.basename(x) for x in SAMPLES]
LONG_SAMPLES=[]
SHORT_SAMPLES=[]

for sample in SAMPLES:
    if os.path.exists(f"data/{sample}/long_reads"):
        LONG_SAMPLES.append(sample)
    else:
        SHORT_SAMPLES.append(sample)

print("Samples with long reads:", LONG_SAMPLES)
print("Samples with short reads:", SHORT_SAMPLES)


# BAKTA_DB=multiext('{}/antifam'.format(BAKTA_DB_PATH),'.h3f','.h3i','.h3m','.h3p') + \
# 		multiext('{}/ncRNA-genes'.format(BAKTA_DB_PATH),'.i1i','.i1f','.i1m','.i1p') + \
# 		multiext('{}/ncRNA-regions'.format(BAKTA_DB_PATH),'.i1i','.i1f','.i1m','.i1p') + \
# 		multiext('{}/rRNA'.format(BAKTA_DB_PATH),'.i1i','.i1f','.i1m','.i1p') + \
# 		multiext('{}/pfam'.format(BAKTA_DB_PATH),'.h3f','.h3i','.h3m','.h3p') + \
# 		['{}/bakta.db'.format(BAKTA_DB_PATH), \
# 		'{}/expert-protein-sequences.dmnd'.format(BAKTA_DB_PATH),\
# 		'{}/sorf.dmnd'.format(BAKTA_DB_PATH), \
# 		'{}/oric.fna'.format(BAKTA_DB_PATH), \
# 		'{}/orit.fna'.format(BAKTA_DB_PATH), \
# 		'{}/rfam-go.tsv'.format(BAKTA_DB_PATH), \
# 		'{}/version.json'.format(BAKTA_DB_PATH)]

# AMRFINDER_DB='{}/amrfinderplus-db/latest/version.txt'.format(BAKTA_DB_PATH)

# ANNOTS=expand("annotated/{sample}/{sample}.tsv",sample=SAMPLES)+ \
# 		expand("annotated/{sample}/{sample}.gff3",sample=SAMPLES)+ \
# 		expand("annotated/{sample}/{sample}.gbff",sample=SAMPLES)+ \
# 		expand("annotated/{sample}/{sample}.embl",sample=SAMPLES)+ \
# 		expand("annotated/{sample}/{sample}.fna",sample=SAMPLES)+ \
# 		expand("annotated/{sample}/{sample}.ffn",sample=SAMPLES)+ \
# 		expand("annotated/{sample}/{sample}.faa",sample=SAMPLES)+ \
# 		expand("annotated/{sample}/{sample}.hypotheticals.tsv",sample=SAMPLES)+ \
# 		expand("annotated/{sample}/{sample}.txt",sample=SAMPLES)+ \
# 		expand("annotated/{sample}/{sample}.json",sample=SAMPLES)

#BANDAGE_IMGS=expand("assembly_viz/{sample}.png",sample=SAMPLES)

#BUSCOS=expand("busco/{sample}/short_summary.specific.bacillales_odb10.{sample}.txt",sample=SAMPLES)

#QUASTS=expand("quast/{sample}/report.txt",sample=SAMPLES)

SHORT_ASSEMBLIES=expand("results/assembly/short_assembly/{sample}.fasta",sample=SHORT_SAMPLES)
LONG_ASSEMBLIES=expand("results/assemby/long_assembly/{sample}.fasta",sample=LONG_SAMPLES)
ASSEMBLIES=expand("results/assembly/{sample}.fasta",sample=SAMPLES)

#GFAS=expand("assemblies/{sample}/assembly.gfa",sample=SAMPLES)
MULTIQC_REPORT=['workflow/reports/multiqc_report.html']

OUTPUTS=SHORT_ASSEMBLIES + MULTIQC_REPORT
#OUTPUTS=ANNOTS+BANDAGE_IMGS+BUSCOS+QUASTS

rule all:
    input: OUTPUTS

# rule bakta_download:
# 	output: BAKTA_DB
# 	shell:"""
# mkdir -p ${{CONDA_PREFIX}}/bakta_db
# bakta_db download --output ${{CONDA_PREFIX}}/bakta_db
# """

# rule amdfinder_download:
# 	input: BAKTA_DB
# 	output: AMRFINDER_DB	
# 	shell:"""
# 	amrfinder_update --database ${{CONDA_PREFIX}}/bakta_db/db/amrfinderplus-db/
# """

rule fastp:
    input:
        fq1='data/{sample}/short_reads/{sample}_1.fastq.gz',
        fq2='data/{sample}/short_reads/{sample}_2.fastq.gz'
    output:
        fq1='results/trimmed_short_reads/{sample}_1.fastq.gz',
        fq2='results/trimmed_short_reads/{sample}_2.fastq.gz',
        json='results/trimmed_short_reads/{sample}_fastp.json'
    container: "docker://quay.io/biocontainers/fastp:1.1.0--heae3180_0"
    threads: 1 # overidden by profile config, but required...
    log: 'workflow/logs/fastp_{sample}.log'
    shell: """
        fastp \
            -i {input.fq1} \
            -I {input.fq2} \
            -o {output.fq1} \
            -O {output.fq2} \
            --json {output.json} \
            --html /dev/null \
            --thread {threads} \
            --disable_quality_filtering \
            --disable_length_filtering \
            --disable_trim_poly_g \
        > {log} 2>&1
    """

rule spades:
    input:
        fq1='results/trimmed_short_reads/{sample}_1.fastq.gz',
        fq2='results/trimmed_short_reads/{sample}_2.fastq.gz'
    output: 
        contigs="results/assembly/short_assembly/{sample}.fasta",
        gfa="results/assembly/short_assembly/{sample}.gfa"
    container: "docker://simonbrandt/spades:v4.2.0"
    log: 'workflow/logs/spades_{sample}.log'
    threads: 1 # overidden by profile config, but required...
    resources:
        mem_mb=1 # overidden by profile config, but required...
    params:
        mode = get_spades_mode
    shell:"""
        (cp -v {input.fq1} $TMPDIR/{wildcards.sample}_1.fastq.gz &&
        cp -v {input.fq2} $TMPDIR/{wildcards.sample}_2.fastq.gz &&
        spades.py \
            -1 $TMPDIR/{wildcards.sample}_1.fastq.gz \
            -2 $TMPDIR/{wildcards.sample}_2.fastq.gz \
            {params.mode} \
            -t {threads} \
            -m {resources.mem_mb} \
            -o $TMPDIR/spades_output &&
        cp -v $TMPDIR/spades_output/contigs.fasta {output.contigs} &&
        cp -v $TMPDIR/spades_output/assembly_graph_with_scaffolds.gfa {output.gfa} &&
        ln -f -s {output.contigs} results/assembly/{wildcards.sample}.fasta ) \
        > {log} 2>&1 
    """

# rule flye:
# 	input: "data/{sample}/{sample}.fastq.gz"
# 	output: "flye_assemblies/{sample}/assembly.fasta"
# 	params: sample="{sample}"
# 	shell:"""
# cp {input} $TMPDIR
# flye --nano-raw $TMPDIR/{params.sample}.fastq.gz --out-dir flye_assemblies/{params.sample} --threads 16
# """

# rule unicycler:
# 	input: 
# 		run1_fq1='data/{sample}/{sample}_run1_1.fastq.gz',
# 		run1_fq2='data/{sample}/{sample}_run1_2.fastq.gz',
# 		run2_fq1='data/{sample}/{sample}_1.fastq.gz',
# 		run2_fq2='data/{sample}/{sample}_2.fastq.gz',
# 		long_fq='data/{sample}/{sample}.fastq.gz',
# 		flye_contigs='flye_assemblies/{sample}/assembly.fasta'
# 	output: "assemblies/{sample}/assembly.gfa",
# 			"assemblies/{sample}/assembly.fasta"
# 	shell:"""
# SAMPLE=$(basename {input.long_fq}|sed 's/.fastq.gz//')

# mkdir $TMPDIR/reads
# mkdir -p assemblies/${{SAMPLE}}

# # unicyler doesn't seem to like concatentated gzipped files, so merge then compress...
# zcat {input.run2_fq1} > $TMPDIR/reads/${{SAMPLE}}_1.fastq
# zcat {input.run2_fq2} > $TMPDIR/reads/${{SAMPLE}}_2.fastq
# zcat {input.run1_fq1} >> $TMPDIR/reads/${{SAMPLE}}_1.fastq
# zcat {input.run1_fq2} >> $TMPDIR/reads/${{SAMPLE}}_2.fastq
# gzip -v $TMPDIR/reads/*fastq
# cp -v {input.long_fq} $TMPDIR/reads
# cp -v {input.flye_contigs} $TMPDIR/reads/flye.fasta
# ls -l $TMPDIR/reads

# unicycler -1 $TMPDIR/reads/${{SAMPLE}}_1.fastq.gz -2 $TMPDIR/reads/${{SAMPLE}}_2.fastq.gz \
# 	-l $TMPDIR/reads/${{SAMPLE}}.fastq.gz  --existing_long_read_assembly $TMPDIR/reads/flye.fasta \
# 	-t 16 --mode bold -o $TMPDIR/output

# cp -Rv $TMPDIR/output/* assemblies/${{SAMPLE}}
# """

# rule annotate:
# 	input: 
# 		contigs="assemblies/{sample}/assembly.fasta",
# 		db=AMRFINDER_DB
# 	params:
# 		sample="{sample}"
# 	output:
# 		multiext("annotated/{sample}/{sample}",'.tsv','.gff3','.gbff','.embl','.fna','.ffn','.faa','.hypotheticals.tsv','.txt','.json')
# 	shell:"""
# bakta --db ${{CONDA_PREFIX}}/bakta_db/db --prefix {params.sample} --output annotated/{params.sample} --threads 16 \
# 	--genus Bacillus --species subtilis --strain {params.sample} --compliant {input.contigs} --locus-tag {params.sample}
# """

# rule bandage:
# 	input: GFAS
# 	output: BANDAGE_IMGS
# 	shell: """
# mkdir $TMPDIR/XDG
# chmod -R 0700 $TMPDIR
# Xvfb :99 &
# export DISPLAY=:99
# export XDG_RUNTIME_DIR=$TMPDIR/XDG
# for GFA in {input}; do
# 	sample=$(dirname $GFA|sed 's|assemblies/||')
# 	echo $sample
# 	Bandage image $GFA assembly_viz/$sample.png --nodewidth 3  --names --fontsize 6
# done
# """

# rule busco:
# 	input: "assemblies/{sample}/assembly.fasta"
# 	output: "busco/{sample}/short_summary.specific.bacillales_odb10.{sample}.txt"
# 	params:
# 		sample="{sample}"
# 	conda: "busco.yaml"
# 	shell: """
# 	busco -m genome -l bacillales_odb10  -o busco/{params.sample} -i {input} -f
# """

# rule quast:
# 	input: 
# 		run1_fq1='data/{sample}/{sample}_run1_1.fastq.gz',
# 		run1_fq2='data/{sample}/{sample}_run1_2.fastq.gz',
# 		run2_fq1='data/{sample}/{sample}_1.fastq.gz',
# 		run2_fq2='data/{sample}/{sample}_2.fastq.gz',
# 		long_fq='data/{sample}/{sample}.fastq.gz',
# 		assembly='assemblies/{sample}/assembly.fasta'
# 	output: "quast/{sample}/latest/report.txt"
# 	params:
# 		sample="{sample}"
# 	shell: """
# mkdir $TMPDIR/reads
# cp {input.run2_fq1} $TMPDIR/reads/{params.sample}_1.fastq.gz
# cp {input.run2_fq2} $TMPDIR/reads/{params.sample}_2.fastq.gz
# cat {input.run1_fq1} >> $TMPDIR/reads/{params.sample}_1.fastq.gz
# cat {input.run1_fq2} >> $TMPDIR/reads/{params.sample}_2.fastq.gz
# cp -v {input.long_fq} $TMPDIR/reads

# quast --pe1 $TMPDIR/reads/{params.sample}_1.fastq.gz --pe2 $TMPDIR/reads/{params.sample}_2.fastq.gz \
# 	--nanopore $TMPDIR/reads/{params.sample}.fastq.gz --circos -L -r reference_data/NCIB3610.fasta \
# 	-o quast/{params.sample} {input.assembly}
# """

rule multiqc:
    input:
        expand('data/{sample}/trimmed_short_reads/{sample}_fastp.json', sample=SAMPLES)
    output:
        'workflow/reports/multiqc_report.html'
    container: "docker://quay.io/biocontainers/multiqc:1.14--pyhdfd78af_0"
    log: 'workflow/logs/multiqc.log'
    shell:
        """
        multiqc data/ \
                --outdir workflow/reports/ \
                --filename multiqc_report.html \
                --force > {log} 2>&1
        """