snakefile: workflow/Snakefile
software-deployment-method: apptainer
apptainer-args: "--bind /cluster/gjb_lab/jabbott/Projects/BugBuilder_II/databases"
latency-wait: 60
show-failed-logs: True
keep-going: False
printshellcmds: True
rerun-incomplete: True
skip-script-cleanup: True
jobname: "BugBuilder_{rule}.{jobid}"
jobs:  200
## DRMAA plugin config
executor: drmaa
drmaa-log-dir: drmaa_logs
drmaa-args: >
  -cwd -j y -pe smp {threads} -mods l_hard mfree {resources.mem_mb}M
## Job Resources
default-resources:
  - threads=1
  - mem_mb=8000
set-threads:
  fastp: 4
  chopper: 4
  nanostat: 4
  kraken: 48
  spades: 16
  flye: 16
  unicycler: 32
  bakta: 16
  busco: 8
  gtdbtk: 24
  quast: 16
set-resources:
  kraken:
    mem_mb: 256000
  spades:
    mem_mb: 64000
  flye:
    mem_mb: 24000
  unicycler:
    mem_mb: 32000


