name: BugBuilder_II
channels:
  - bioconda
  - conda-forge
dependencies:
  - beautifulsoup4
  - biopython
  - drmaa
  - lxml
  - openpyxl
  - pandas
  - python
  - requests
  - requests-toolbelt
  - snakemake
  - snakemake-executor-plugin-drmaa
  - snakemake-interface-common
  - snakemake-interface-executor-plugins
  - snakemake-interface-logger-plugins
  - snakemake-interface-report-plugins
  - snakemake-interface-scheduler-plugins
  - snakemake-interface-storage-plugins
  - snakemake-minimal
  - wget
