title: "Bacterial Genome Assembly Report"
disable_version_detection: true
versions_table_group_header: "Software Versions from workflow containers"
custom_content:
    rna_representation:
        file_format: 'tsv'
        section_name: 'RNA Representation'
        data_format: 'table'
        plot_type: 'table'
        fn: 'rna_representation_mqc.tsv'
module_order:
  - fastqc
  - fastp
  - kraken
  - nanostat
  - bakta
  - quast
  - checkm2
  - busco
  - rna_representation
  - gtdbtk
exclude_modules:
  - sambamba
  - samtools
# general statistics table setup
table_columns_visible:
  kraken: False
  trimmed_nanostat: False
# Squash mutliple sample rows into one row per sample...
table_sample_merge:
  "R1": "_1"
  "R2": "_2"
  "long_reads": "_nanostat"