title: "Bacterial Genome Assembly Report"
disable_version_detection: true
versions_table_group_header: "Software Versions from workflow containers"
exclude_modules:
  - sambamba
  - samtools
module_order:
  - fastp
  - nanostat
  - quast
  - checkm2
  - busco
  - bakta
  - gtdbtk